require 'yaml'
require 'hash'
require 'string'
require 'enzyme'

module Config extend self

  GLOBAL_FILENAME = "#{ENV['HOME']}/.enzyme.yml"
  PROJECT_FILENAME = "./.enzyme.yml"

  def run()
    global = ARGV.delete('--global')
    ARGV.reject { |x| x.start_with?("-") }
    key = ARGV.shift
    value = ARGV.shift

    unless value === nil
      set(key, value, global)
      puts "Set '#{key}' to '#{value}'."
    else
      val = get(key, global)
      if val.is_a?(Array) || val.is_a?(Hash)
        puts val.to_hash.to_yaml
      else
        puts val.to_s
      end
    end
    puts
  end

  # Check that the given setting has been set, if it hasn't prompt the user to give it a value.
  # - key: The setting the check & set.
  # - global: Where to set the setting. See the #set method.
  def prompt_for(key, global=false)
    unless is_set?(key)
      print "Set '#{key}': "
      set(key, gets.strip, global)
      puts
    end
  end

  # Checks if the given setting has a value.
  # - key: The setting to check.
  def is_set?(key)
    (get(key).nil? || get(key).empty?) ? false : true
  end

  # Gets the value of a given setting.
  # - key: The setting to get.
  # - global: If true, get return value as it's set in the global config file.
  def get(key, global=false)
    s = global ? (YAML.load_file(GLOBAL_FILENAME) || {}) : $settings
    key.to_s.split('.').each do |o|
      return nil if s[o].nil?
      s = s[o]
    end
    s
  end

  # Sets the value of the given setting.
  # - key: The setting to set.
  # - value: The value to set the value to.
  # - global: If true, set this setting in the global config file, otherwise the project's.
  def set(key, value, global=false, temp=false)
    # FIXME: This could be simplified... heaps.
    new_settings = { 'enzyme_version' => $version }
    current_hash = new_settings
    keys = key.to_s.split(".")
    keys.each do |key|
      key = key.to_i if key.is_i?
      current_hash[key] = (key == keys.last) ? value : {}
      current_hash = current_hash[key]
    end

    $settings = $settings.deep_merge(new_settings)

    unless temp
      filename = global ? GLOBAL_FILENAME : PROJECT_FILENAME

      # TODO: Check we're in a project folder before making the project config file.
      `touch "#{filename}"` unless File.exists?(filename)

      settings = YAML.load_file(filename) || {}
      settings = settings.deep_merge(new_settings)

      File.open(filename, "w") do |f|
        f.write("\# Generated by Enzyme.\n")
        f.write(settings.to_yaml)
      end
    end
  end

end

Enzyme.register('config', Config) do
  puts "#{$format.bold}SYNOPSIS#{$format.normal}"
  puts '     enzyme config [<key> [<value> [--global]]]'
  puts
  puts "#{$format.bold}EXAMPLES#{$format.normal}"
  puts '     enzyme config user dave --global'
  puts
  puts '     enzyme config user'
  puts '     > dave'
  puts
  puts '     enzyme config project_name my_project'
  puts
  puts '     enzyme config project_name'
  puts '     > my_project'
  puts
end