require 'enzyme'

module Config extend self

  def run()
    file = ARGV.delete((ARGV & ['--global', '--organisation', '--project']).first)
    ARGV.each { |x| raise UnknownOption.new(x) if x.start_with?("-") }
    key = ARGV.shift
    value = ARGV.shift
    ARGV.each { |x| raise UnknownArgument.new(x) }

    if file.nil?
      file = $system_settings.config.project.exists ? "project" : "global"
    else
      file = file.to_s[/[a-z]+$/]
    end

    raise ConfigFileNotFound.new($system_settings.config[file].path) unless $system_settings.config[file].exists

    path = $system_settings.config[file].path

    unless value === nil
      set(key, value, path)
      puts "Set '#{key}' to '#{value}' in '#{path}'."
    else
      val = get(key, path)
      if val.nil?
        puts "<nil>"
      elsif val.is_a?(Array) || val.is_a?(Hash)
        puts val.to_hash.to_yaml
      else
        puts val.to_s
      end
    end
  end

  # Gets the value of a given setting.
  # - key: The setting to get.
  # - path: The path to the config file to get the setting from.
  def get(key, path)
    s = path ? (YAML.load_file(path) || {}) : $settings
    key.to_s.split('.').each do |o|
      return nil if s[o].nil?
      s = s[o]
    end
    s
  end

  # Sets the value of the given setting.
  # - key: The setting to set.
  # - value: The value to set the setting to.
  # - path: The path to the config file to set the setting in.
  def set(key, value, path)
    # FIXME: This could be simplified... heaps.
    new_settings = { 'enzyme_version' => $system_settings.version }
    current_hash = new_settings
    keys = key.to_s.split(".")
    keys.each do |key|
      key = key.to_i if key.is_i?
      current_hash[key] = (key == keys.last) ? value : {}
      current_hash = current_hash[key]
    end

    $settings = $settings.deep_merge(new_settings)

    # Reload the settings to avoid including temporary settings.
    settings = YAML.load_file(path) || {}
    # Merge in the new settings.
    settings = settings.deep_merge(new_settings)

    # Save the settings to the config file.
    write(path, settings)
  end

  def write(path, settings)
    File.open(path, "w") do |f|
      f.write("\# Generated by Enzyme.\n")
      f.write(settings.to_yaml)
    end
  end

end

Enzyme.register('config', Config) do
  puts "#{$format.bold}SYNOPSIS#{$format.normal}"
  puts '       enzyme config [--global|--organisation|--project]'
  puts '       enzyme config <key> [--global|--organisation|--project]'
  puts '       enzyme config <key> <value> [--global|--organisation|--project]'
  puts
  puts "#{$format.bold}DESCRIPTION#{$format.normal}"
  puts "       In its first form the config command dumps the settings."
  puts
  puts "       In its second form the config command prints the value of a given key."
  puts
  puts "       In its third form the config command sets the value of a given key."
  puts
  puts "#{$format.bold}EXAMPLES#{$format.normal}"
  puts "        1. Get the value of the 'short_name' setting:"
  puts
  puts "               $ enzyme config short_name"
  puts "               dave"
  puts
  puts "        2. Set the value of the 'short_name' setting:"
  puts
  puts "               $ enzyme config short_name jill"
  puts "               Set 'short_name' to 'jill' in '/Users/jill/.enzyme.yml'."
  puts
  puts "        3. Get the value of the 'sync.projects_directory' setting in the organisation config file:"
  puts
  puts "               $ enzyme config sync.projects_directory --organisation"
  puts "               Projects"
end
